# Generated by Django 6.0.7 on 2026-08-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donor_base_currency_globaluser_mfi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globaluser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='historicalglobaluser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user', 'verbose_name_plural': 'historical users'},
        ),
    ]
