# Generated by Django 6.0.7 on 2026-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_alter_globaluser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mfi',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='aom',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('AOM_STAFF', 'AoM Staff'), ('DONOR_STAFF', 'Donor Staff'), ('MFI_ADMIN', 'MFI Admin'), ('MFI_MANAGER', 'MFI Manager'), ('LOAN_OFFICER', 'Loan Officer')], db_index=True, default='SUPER_ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalglobaluser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('AOM_STAFF', 'AoM Staff'), ('DONOR_STAFF', 'Donor Staff'), ('MFI_ADMIN', 'MFI Admin'), ('MFI_MANAGER', 'MFI Manager'), ('LOAN_OFFICER', 'Loan Officer')], db_index=True, default='SUPER_ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmfi',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='mfi',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mfi',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='globaluser',
            index=models.Index(fields=['role', 'mfi'], name='core_global_role_ecd676_idx'),
        ),
        migrations.AddIndex(
            model_name='globaluser',
            index=models.Index(fields=['role', 'aom'], name='core_global_role_e4aa3b_idx'),
        ),
    ]
