# Generated by Django 6.0.7 on 2026-08-11 17:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aom_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aomreport',
            name='base_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='aomreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_aom_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aomreport',
            name='period',
            field=models.DateField(help_text='First day of the month', validators=[core.models.first_day_of_month_validator]),
        ),
        migrations.AlterField(
            model_name='aomreport',
            name='source_reports',
            field=models.ManyToManyField(blank=True, related_name='aom_consolidations', to='core.mfireport'),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='base_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_donor_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='period',
            field=models.DateField(help_text='First day of the month', validators=[core.models.first_day_of_month_validator]),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='source_reports',
            field=models.ManyToManyField(blank=True, related_name='donor_consolidations', to='core.aomreport'),
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('AOM_STAFF', 'AoM Staff'), ('DONOR_STAFF', 'Donor Staff'), ('MFI_ADMIN', 'MFI Admin'), ('MFI_MANAGER', 'MFI Manager'), ('LOAN_OFFICER', 'Loan Officer')], db_index=True, default='LOAN_OFFICER', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalaomreport',
            name='base_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalaomreport',
            name='period',
            field=models.DateField(help_text='First day of the month', validators=[core.models.first_day_of_month_validator]),
        ),
        migrations.AlterField(
            model_name='historicaldonorreport',
            name='base_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicaldonorreport',
            name='period',
            field=models.DateField(help_text='First day of the month', validators=[core.models.first_day_of_month_validator]),
        ),
        migrations.AlterField(
            model_name='historicalglobaluser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('AOM_STAFF', 'AoM Staff'), ('DONOR_STAFF', 'Donor Staff'), ('MFI_ADMIN', 'MFI Admin'), ('MFI_MANAGER', 'MFI Manager'), ('LOAN_OFFICER', 'Loan Officer')], db_index=True, default='LOAN_OFFICER', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmfireport',
            name='base_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalmfireport',
            name='local_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalmfireport',
            name='period',
            field=models.DateField(help_text='First day of the month, e.g. 2026-08-01', validators=[core.models.first_day_of_month_validator]),
        ),
        migrations.AlterField(
            model_name='mfireport',
            name='base_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='mfireport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mfireport',
            name='local_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='mfireport',
            name='period',
            field=models.DateField(help_text='First day of the month, e.g. 2026-08-01', validators=[core.models.first_day_of_month_validator]),
        ),
    ]
