# Generated by Django 6.0.7 on 2026-08-15 04:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aomreport_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDonorContribution',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('contribution_date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Wire transfer reference or other external reference.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.aom')),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.donor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical donor contribution',
                'verbose_name_plural': 'historical donor contributions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMFIDisbursement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('ACT', 'Active'), ('RPD', 'Repaid'), ('DEF', 'Defaulted'), ('CAN', 'Cancelled')], default='PND', max_length=3)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.aom')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mfi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.mfi')),
            ],
            options={
                'verbose_name': 'historical mfi disbursement',
                'verbose_name_plural': 'historical mfi disbursements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MFIDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('ACT', 'Active'), ('RPD', 'Repaid'), ('DEF', 'Defaulted'), ('CAN', 'Cancelled')], default='PND', max_length=3)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='core.aom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disbursements', to=settings.AUTH_USER_MODEL)),
                ('mfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='core.mfi')),
            ],
            options={
                'db_table': 'core_mfidisbursement',
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMFIDisbursementRepayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('expected_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('days_overdue', models.IntegerField(default=0)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disbursement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.mfidisbursement')),
            ],
            options={
                'verbose_name': 'historical mfi disbursement repayment',
                'verbose_name_plural': 'historical mfi disbursement repayments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MFIDisbursementRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('expected_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('days_overdue', models.IntegerField(default=0)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.mfidisbursement')),
            ],
            options={
                'db_table': 'core_mfidisbursementrepayment',
                'ordering': ['disbursement', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='DonorContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('contribution_date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Wire transfer reference or other external reference.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.aom')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.donor')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_donor_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_donorcontribution',
                'ordering': ['-contribution_date'],
                'indexes': [models.Index(fields=['donor', 'aom'], name='core_donorc_donor_i_236c6e_idx'), models.Index(fields=['contribution_date'], name='core_donorc_contrib_a1b7d5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mfidisbursement',
            index=models.Index(fields=['aom', 'mfi'], name='core_mfidis_aom_id_ac43b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mfidisbursement',
            index=models.Index(fields=['status'], name='core_mfidis_status_ade8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='mfidisbursementrepayment',
            index=models.Index(fields=['due_date', 'is_paid'], name='core_mfidis_due_dat_7cf87e_idx'),
        ),
        migrations.AddIndex(
            model_name='mfidisbursementrepayment',
            index=models.Index(fields=['days_overdue'], name='core_mfidis_days_ov_57668d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mfidisbursementrepayment',
            unique_together={('disbursement', 'installment_number')},
        ),
    ]
