# Generated by Django 6.0.7 on 2026-08-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aom',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='historicalaom',
            name='donor',
        ),
        migrations.AddField(
            model_name='aom',
            name='donors',
            field=models.ManyToManyField(blank=True, related_name='aoms', to='core.donor'),
        ),
    ]
