# Generated by Django 6.0.7 on 2026-08-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_branch',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_officers', to='tenants.branch')),
            ],
            options={
                'db_table': 'tenants_loanofficer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('borrower_type', models.CharField(choices=[('IND', 'Individual'), ('GRP', 'Group')], default='IND', max_length=3)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('region_1', models.CharField(max_length=255)),
                ('region_2', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('geo_type', models.CharField(max_length=100)),
                ('beneficiaries', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenants.branch')),
                ('loan_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenants.loanofficer')),
            ],
            options={
                'db_table': 'tenants_member',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=50, unique=True)),
                ('product_type', models.CharField(max_length=100)),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('CLS', 'Closed'), ('DEF', 'Defaulted'), ('PND', 'Pending')], default='PND', max_length=3)),
                ('water_component', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term', models.IntegerField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='tenants.branch')),
                ('loan_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='tenants.loanofficer')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='tenants.member')),
            ],
            options={
                'db_table': 'tenants_loan',
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name', 'region_1', 'region_2'], name='tenants_mem_name_429df4_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_id'], name='tenants_mem_member__5f9b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_number'], name='tenants_loa_loan_nu_04ea4b_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='tenants_loa_status_9e8c76_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'status'], name='tenants_loa_member__f27e0d_idx'),
        ),
    ]
