# Generated by Django 6.0.7 on 2026-08-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_street',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geo_type', models.CharField(choices=[('URBAN', 'Urban'), ('RURAL', 'Rural'), ('PERI_URBAN', 'Peri-Urban')], default='RURAL', max_length=20)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_ward',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.AddField(
            model_name='member',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='geo_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='region_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='region_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='ward',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='tenants.region')),
            ],
            options={
                'db_table': 'tenants_district',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='tenants.street'),
        ),
        migrations.AlterField(
            model_name='member',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenants.street'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['street'], name='tenants_mem_street__e3f83c_idx'),
        ),
        migrations.AddField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='tenants.district'),
        ),
        migrations.AddField(
            model_name='street',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='tenants.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('district', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('ward', 'name')},
        ),
    ]
