# Generated by Django 6.0.7 on 2026-08-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_historicalbranch_historicaldistrict_historicalloan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalward',
            name='geo_type',
            field=models.CharField(choices=[('URB', 'Urban'), ('RUR', 'Rural'), ('PER', 'Peri-Urban')], default='URB', max_length=50),
        ),
        migrations.AlterField(
            model_name='ward',
            name='geo_type',
            field=models.CharField(choices=[('URB', 'Urban'), ('RUR', 'Rural'), ('PER', 'Peri-Urban')], default='URB', max_length=50),
        ),
    ]
