# Generated by Django 6.0.7 on 2026-08-11 17:31

import django.db.models.deletion
import tenants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_historicalward_geo_type_alter_ward_geo_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanadjustment',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to=tenants.models.TenantUploadPath('loan_adjustments')),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='file',
            field=models.FileField(upload_to=tenants.models.TenantUploadPath('loan_documents')),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
