# Generated by Django 6.0.7 on 2026-08-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_loanadjustment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloan',
            name='loan_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
