'use client';

import { useState } from 'react';
import { toast } from 'sonner';
import { Check, X } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  useSharedMFIReports, useSharedAoMReports, useSharedDonorReports,
  useApproveMFIReport, useRejectMFIReport,
  useApproveAoMReport, useApproveDonorReport,
} from '@/hooks/useSharedData';
import { useAuthStore } from '@/hooks/useAuthStore';
import { canApproveAomReport, canApproveDonorReport, canApproveMfiReport } from '@/lib/permissions';
import type { AoMReport, DonorReport, MFIReport, ReportStatus } from '@/types';

type Tab = 'mfi' | 'aom' | 'donor';

const statusVariant = (status: ReportStatus) =>
  status === 'APPROVED' ? 'success'
  : status === 'REJECTED' ? 'destructive'
  : status === 'SUBMITTED' ? 'default'
  : 'secondary';

export default function ConsolidatedReportsPage() {
  const [tab, setTab] = useState<Tab>('mfi');
  const user = useAuthStore((state) => state.user);

  return (
    <div className="max-w-5xl mx-auto p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-900">Consolidated Reports</h1>
        <p className="text-slate-500">
          Reports across the organizations you oversee. Approving a report
          requires a different role than the one that submitted it.
        </p>
      </div>

      <div className="flex gap-2 mb-6 border-b border-slate-200">
        {(['mfi', 'aom', 'donor'] as Tab[]).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-4 py-2.5 text-sm font-medium border-b-2 -mb-px transition-colors capitalize ${
              tab === t ? 'border-violet-600 text-violet-600' : 'border-transparent text-slate-500 hover:text-slate-700'
            }`}
          >
            {t} Reports
          </button>
        ))}
      </div>

      {tab === 'mfi' && <MFIReportsTab canApprove={canApproveMfiReport(user)} />}
      {tab === 'aom' && <AoMReportsTab canApprove={canApproveAomReport(user)} />}
      {tab === 'donor' && <DonorReportsTab canApprove={canApproveDonorReport(user)} />}
    </div>
  );
}

function MFIReportsTab({ canApprove }: { canApprove: boolean }) {
  const { data, isLoading } = useSharedMFIReports();
  const approve = useApproveMFIReport();
  const reject = useRejectMFIReport();

  const act = async (fn: typeof approve.mutateAsync, id: number, verb: string) => {
    try {
      await fn(id);
      toast.success(`Report ${verb}`);
    } catch {
      toast.error(`Failed to ${verb.replace('ed', '')} report`);
    }
  };

  if (isLoading) return <LoadingState />;
  if (!data?.results?.length) return <EmptyState label="No MFI reports in your scope." />;

  return (
    <div className="grid gap-3">
      {data.results.map((r: MFIReport) => (
        <Card key={r.id}>
          <CardContent className="pt-6 flex items-center justify-between">
            <div>
              <p className="font-medium text-slate-900">
                {r.mfi_name} &middot; {new Date(r.period).toLocaleDateString('default', { month: 'long', year: 'numeric' })}
              </p>
              <p className="text-sm text-slate-500">
                Generated by {r.generated_by_name || 'system'}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant={statusVariant(r.status)}>{r.status}</Badge>
              {canApprove && r.status === 'SUBMITTED' && (
                <>
                  <Button size="sm" variant="outline" onClick={() => act(approve.mutateAsync, r.id, 'approved')}>
                    <Check className="h-3.5 w-3.5 mr-1" /> Approve
                  </Button>
                  <Button size="sm" variant="outline" onClick={() => act(reject.mutateAsync, r.id, 'rejected')}>
                    <X className="h-3.5 w-3.5 mr-1" /> Reject
                  </Button>
                </>
              )}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}

function AoMReportsTab({ canApprove }: { canApprove: boolean }) {
  const { data, isLoading } = useSharedAoMReports();
  const approve = useApproveAoMReport();

  if (isLoading) return <LoadingState />;
  if (!data?.results?.length) return <EmptyState label="No AoM reports in your scope." />;

  return (
    <div className="grid gap-3">
      {data.results.map((r: AoMReport) => (
        <Card key={r.id}>
          <CardContent className="pt-6 flex items-center justify-between">
            <div>
              <p className="font-medium text-slate-900">
                {r.aom_name} &middot; {new Date(r.period).toLocaleDateString('default', { month: 'long', year: 'numeric' })}
              </p>
              <p className="text-sm text-slate-500">Generated by {r.generated_by_name || 'system'}</p>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant={statusVariant(r.status)}>{r.status}</Badge>
              {canApprove && r.status === 'SUBMITTED' && (
                <Button
                  size="sm"
                  variant="outline"
                  onClick={async () => {
                    try {
                      await approve.mutateAsync(r.id);
                      toast.success('Report approved');
                    } catch {
                      toast.error('Failed to approve report');
                    }
                  }}
                >
                  <Check className="h-3.5 w-3.5 mr-1" /> Approve
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}

function DonorReportsTab({ canApprove }: { canApprove: boolean }) {
  const { data, isLoading } = useSharedDonorReports();
  const approve = useApproveDonorReport();

  if (isLoading) return <LoadingState />;
  if (!data?.results?.length) return <EmptyState label="No donor reports in your scope." />;

  return (
    <div className="grid gap-3">
      {data.results.map((r: DonorReport) => (
        <Card key={r.id}>
          <CardContent className="pt-6 flex items-center justify-between">
            <div>
              <p className="font-medium text-slate-900">
                {r.donor_name} &middot; {new Date(r.period).toLocaleDateString('default', { month: 'long', year: 'numeric' })}
              </p>
              <p className="text-sm text-slate-500">Generated by {r.generated_by_name || 'system'}</p>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant={statusVariant(r.status)}>{r.status}</Badge>
              {canApprove && r.status === 'SUBMITTED' && (
                <Button
                  size="sm"
                  variant="outline"
                  onClick={async () => {
                    try {
                      await approve.mutateAsync(r.id);
                      toast.success('Report approved');
                    } catch {
                      toast.error('Failed to approve report');
                    }
                  }}
                >
                  <Check className="h-3.5 w-3.5 mr-1" /> Approve
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}

function LoadingState() {
  return (
    <div className="text-center py-8">
      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-violet-600 mx-auto"></div>
    </div>
  );
}

function EmptyState({ label }: { label: string }) {
  return <div className="text-center py-8 text-sm text-slate-500">{label}</div>;
}
